# Data Analyst role

- Level 3 we will learn the skill set required for Data Analyst Role
   - Read from any where (Big data,rdbms,nosql databases,files,api calls ..etc
   - Data transformations/manipulations
   - Present data in graphical format

## Numpy

[https://www.numpy.org/](https://www.numpy.org/)
- Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.
- Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.

### Additional Recommended Resources:

[https://docs.scipy.org/doc/numpy/reference/](https://docs.scipy.org/doc/numpy/reference/)

# ex1: python list is failed

In [3]:
weights=[70,80,90]
heights=[1.6,1.7,1.8]
bmi=weights/(heights**2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### Ex2 : 

In [4]:
True+False

1

In [5]:
True+True+True

3

In [6]:
sum(35<[30,40,50,60])

TypeError: '<' not supported between instances of 'int' and 'list'

## Solution for above problem

In [21]:
import numpy as np

np_weights = np.array(weights)
print(np_weights)
print(type(np_weights))
print(np_weights.dtype)
print(np_weights.ndim)
print(np_weights.shape)
print(np_weights[0])

[70 80 90]
<class 'numpy.ndarray'>
int32
1
(3,)
70


In [13]:
np.array?

In [19]:
np_heights = np.array(heights)
print(np_heights)
print(type(np_heights))
print(np_heights.dtype)
print(np_heights.ndim) 
print(np_heights.shape) 
print(np_heights[0])     

[1.6 1.7 1.8]
<class 'numpy.ndarray'>
float64
1
(3,)
1.6


In [24]:
bmi=np_weights/(np_heights**2)
print(bmi)

[27.34375    27.6816609  27.77777778]


[27.34375    27.6816609  27.77777778]


## Ex:2

In [25]:
sum(35<np.array([30,40,50,60,70]))

4

In [ ]:
np.array?

## 2.Numpy listis homogeneous multidimensional array

- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers

In [28]:
a_list = [10,10.33,"python",1+2J,True,[10,30]]
a_list

[10, 10.33, 'python', (1+2j), True, [10, 30]]

In [31]:
import numpy as np
a_np_list = np.array([10,10.33])  # i given input 10 it is int 10.33 it is float
a_np_list                         # here integer converted into float 

array([10.  , 10.33])

In [32]:
a_np_list = np.array([10,10.33,"pawan"])
a_np_list

array(['10', '10.33', 'pawan'], dtype='<U32')

# 3.Numpy 

# how to identify the given array is 1d array

In [53]:
od=np.arange(0,12,2)

print(od)
print(type(od))
print(od.ndim)
print(od.shape)
print(type(od.shape))

[ 0  2  4  6  8 10]
<class 'numpy.ndarray'>
1
(6,)
<class 'tuple'>


In [45]:
od

array([ 0,  2,  4,  6,  8, 10])

In [54]:
type(od)

numpy.ndarray

In [47]:
od.ndim

1

In [40]:
od.shape

(6,)

In [39]:
type(od.shape)

tuple

### reading numpy 1D array items

In [57]:
#index method
od[1]

2

In [58]:
#slice method
od[0:3]

array([0, 2, 4])

In [59]:
#fancy method
od[[1,3]]

array([2, 6])

### numpy array is mutable

In [60]:
od[1]=200
od

array([  0, 200,   4,   6,   8,  10])

## How to identify the given array is 2D

- table, matrix,black and white image

In [73]:
td=np.arange(0,24,2).reshape(3,4)
print(td)
print(type(td))
print(td.ndim)
print(td.shape)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
<class 'numpy.ndarray'>
2
(3, 4)


In [68]:
td

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [64]:
type(td)

numpy.ndarray

In [65]:
td.ndim

2

In [66]:
td.shape

(3, 4)

### EX2:- Animal table

In [79]:
                #weight   #legs  #hair column
at = np.array([[1000, 80],[4,2],[30,1.5]])
print(at)
print(type(at))
print(at.ndim)
print(at.shape)

[[1000.    80. ]
 [   4.     2. ]
 [  30.     1.5]]
<class 'numpy.ndarray'>
2
(3, 2)


In [ ]:
# right to left explaination
# 2(no. of items in 1d array)(no.of rows)
# 3(no. of 1d arrays in 2d aaray)(no.of columns)

### Accessing of 2D

In [ ]:
#1st row
td[0]

In [ ]:
#2nd row
td[2]

In [ ]:
td[2][2]

In [ ]:
td[:,2]  #all rows 3rd column

In [ ]:
td[1,:]  #2nd row all columns

In [ ]:
#slice method
td[0:2]

## How toidentify the given array is 3D

In [86]:
thd=np.arange(24).reshape(2,3,4)
print(thd)
print(thd.ndim)
print(thd.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
(2, 3, 4)


In [87]:
thd

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [82]:
thd.ndim

3

In [83]:
thd.shape

(3, 4, 2)

### 4D

In [91]:
np.arange(64).reshape(4,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [90]:
fd = np.arange(48).reshape(2,2,3,4)
fd

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]],


       [[[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],

        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]]])

# 4.numpy array occupies less memory

In [ ]:
py_lst= list(range(200))

In [ ]:
min(py_lst),max(py_lst),len(py_lst)

In [ ]:
import numpy as np
np_arr=np.array(list(range(100)))

In [ ]:
min(np_arr),max(np_arr),len(np_arr)

In [ ]:
import sys

In [ ]:
print(sys.getsizeof(py_lst))
print(sys.getsizeof(np_arr))